### ISSUE TITLE
[BE] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by suhyunsim** [codesquad-member-2020/airbnb-05#16]
# TODO

## 의존성 추가
- [x] Lombok
- [x] MySQL Driver
- [x] Spring Data JDBC
- [x] Spring Web

## logback 설정
- [x] logback.xml 파일 추가

## Mysql 연결
- [x] application.properties에 DB 정보 추가
